### ISSUE TITLE
randomFirst method return string

### ISSUE THREAD

**Issue by itsmirik** [lazerg/laravel-enum-pro#2]
PHP version: ^8.1
Laravel version: 9.2
Package version: 0.3

I've created enum:

```
    case SM = " 10-13 ";
    case MD = " 14-19 ";
    case LG = " 20-26 ";
    case XL = " 28 ";
```
I can't get the first random element, because in your [`randomFirst()`](https://github.com/lazerg/laravel-enum-pro/blob/v0.3.0/src/EnumRandom.php#L30) method return type is Integer

**Comment by lazerg** [comment]
I see... It can be a critical issue if you use string type. Please create a pull request for this issue and I will merge it. Thank you for reporting.
